Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -29,17 +29,23 @@ jobs:
           
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
-        
-      - name: Extract version from commit messages
+
+      - name: Extract version from tag or commit message
         run: |
-          VERSION=$(git log -1 --pretty=format:%B)
-          if [[ ! -z "$VERSION" ]]; then
-            echo "VERSION=$VERSION" >> $GITHUB_ENV
+          echo "GITHUB_REF: ${GITHUB_REF}"
+          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
+            VERSION=${GITHUB_REF#refs/tags/}
           else
-            echo "No version found in the commit message"
+            VERSION=$(git log -1 --pretty=format:%B | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' || echo "")
+          fi
+          if [[ -z "$VERSION" ]]; then
+            echo "No version found in the commit message or tag"
             exit 1
           fi
-          
+          VERSION=${VERSION//[[:space:]]/}  # Remove any spaces
+          echo "Using version: $VERSION"
+          echo "VERSION=${VERSION}" >> $GITHUB_ENV
+
       - name: Build and push
         uses: docker/build-push-action@v5
         with:
@@ -51,47 +57,127 @@ jobs:
   deploy:
     needs: build-and-push
     name: Deploy to Kubernetes
-    if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags/1')
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-latest
+    if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v')
     steps:
-      - name: Checkout
+      - name: Checkout code
         uses: actions/checkout@v4
-        
-      - name: Configure Kubernetes
-        uses: azure/k8s-set-context@v4
-        with:
-          method: kubeconfig
-          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
 
-      - name: Extract version from commit messages
+      - name: List files in the working directory
         run: |
-          VERSION=$(git log -1 --pretty=format:%B)
-          if [[ ! -z "$VERSION" ]]; then
-            echo "VERSION=$VERSION" >> $GITHUB_ENV
+          ls -la
+
+      - name: Set up Kubernetes
+        uses: azure/setup-kubectl@v3
+        with:
+          version: 'v1.21.0'
+
+      - name: Extract version from tag or commit message
+        run: |
+          echo "GITHUB_REF: ${GITHUB_REF}"
+          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
+            VERSION=${GITHUB_REF#refs/tags/}
           else
-            echo "No version found in the commit message"
+            VERSION=$(git log -1 --pretty=format:%B | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' || echo "")
+          fi
+          if [[ -z "$VERSION" ]]; then
+            echo "No version found in the commit message or tag"
             exit 1
           fi
+          VERSION=${VERSION//[[:space:]]/}  # Remove any spaces
+          echo "Using version: $VERSION"
+          echo "VERSION=${VERSION}" >> $GITHUB_ENV
 
-      - name: Replace image tag in deploy.yaml
-        if: env.DEPLOY == 'false'
-       
+      - name: Replace image tag in deployment.yaml
         run: |
-          sed -i "s|image: slavazakariev/nginx-app:.*|image: ${{ env.IMAGE_TAG }}|" ./nginx-app/deploy.yaml
-        env:
-          IMAGE_TAG: slavazakariev/nginx-app:${{ env.VERSION }}
-      
+          if [ ! -f ./deploy/deployment.yaml ]; then
+            echo "deployment.yaml not found in the current directory"
+            exit 1
+          fi
+          sed -i "s|image: slavazakariev/nginx-app:.*|image: ${{ env.IMAGE_TAG }}:${{ env.VERSION }}|" ./deploy/deployment.yaml
+
       - name: Create kubeconfig
         run: |
           mkdir -p $HOME/.kube/
+
       - name: Authenticate to Kubernetes cluster
         env:
           KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
         run: |
-          echo "${KUBE_CONFIG_DATA}" > ${HOME}/.kube/config
+          echo "${KUBE_CONFIG_DATA}" | base64 --decode > ${HOME}/.kube/config
+          kubectl config view
+          kubectl get nodes
+
       - name: Apply Kubernetes manifests
         run: |
-          kubectl apply -f ./nginx-app/deploy.yaml 
+          kubectl apply -f ./deploy/deployment.yaml
+          kubectl get daemonsets -n monitoring
+          kubectl get pods -n monitoring
+          kubectl describe daemonset myapp -n monitoring
+          kubectl describe service myapp-service -n monitoring
+        
+  #     - name: Extract version from commit messages
+  #       run: |
+  #         VERSION=$(git log -1 --pretty=format:%B)
+  #         if [[ ! -z "$VERSION" ]]; then
+  #           echo "VERSION=$VERSION" >> $GITHUB_ENV
+  #         else
+  #           echo "No version found in the commit message"
+  #           exit 1
+  #         fi
+          
+  #     - name: Build and push
+  #       uses: docker/build-push-action@v5
+  #       with:
+  #         context: .
+  #         file: ./Dockerfile
+  #         push: true
+  #         tags: ${{ env.IMAGE_TAG }}:${{ env.VERSION }}
+
+  # deploy:
+  #   needs: build-and-push
+  #   name: Deploy to Kubernetes
+  #   if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags/1')
+  #   runs-on: ubuntu-22.04
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+        
+  #     - name: Configure Kubernetes
+  #       uses: azure/k8s-set-context@v4
+  #       with:
+  #         method: kubeconfig
+  #         kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
+
+  #     - name: Extract version from commit messages
+  #       run: |
+  #         VERSION=$(git log -1 --pretty=format:%B)
+  #         if [[ ! -z "$VERSION" ]]; then
+  #           echo "VERSION=$VERSION" >> $GITHUB_ENV
+  #         else
+  #           echo "No version found in the commit message"
+  #           exit 1
+  #         fi
+
+  #     - name: Replace image tag in deploy.yaml
+  #       if: env.DEPLOY == 'false'
+       
+  #       run: |
+  #         sed -i "s|image: slavazakariev/nginx-app:.*|image: ${{ env.IMAGE_TAG }}|" ./nginx-app/deploy.yaml
+  #       env:
+  #         IMAGE_TAG: slavazakariev/nginx-app:${{ env.VERSION }}
+      
+  #     - name: Create kubeconfig
+  #       run: |
+  #         mkdir -p $HOME/.kube/
+  #     - name: Authenticate to Kubernetes cluster
+  #       env:
+  #         KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
+  #       run: |
+  #         echo "${KUBE_CONFIG_DATA}" > ${HOME}/.kube/config
+  #     - name: Apply Kubernetes manifests
+  #       run: |
+  #         kubectl apply -f ./nginx-app/deploy.yaml 
       
       # - name: Deploy to Kubernetes with Helm
       #   run: |
